import "server-only";

import JSZip from "jszip";
import type { ProjectFile } from "./db/schema";

interface FileStructure {
  path: string;
  content: string;
  type?: string;
}

/**
 * Generates a ZIP file from a project's file structure
 */
export async function generateProjectZip(files: FileStructure[]): Promise<Blob> {
  const zip = new JSZip();

  // Add all project files
  for (const file of files) {
    zip.file(file.path, file.content);
  }

  // Generate the ZIP blob
  const blob = await zip.generateAsync({ type: "blob" });
  return blob;
}

/**
 * Generates a package.json file based on detected dependencies
 */
export function generatePackageJson(files: FileStructure[]): string {
  const dependencies: Record<string, string> = {
    react: "^19.0.0",
    "react-dom": "^19.0.0",
    next: "^16.0.0",
  };

  const devDependencies: Record<string, string> = {
    "@types/node": "^25.0.0",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    typescript: "^5.0.0",
    tailwindcss: "^4.0.0",
  };

  // Detect additional dependencies from file content
  const allContent = files.map((f) => f.content).join("\n");

  if (allContent.includes("lucide-react")) {
    dependencies["lucide-react"] = "latest";
  }

  if (allContent.includes("@radix-ui")) {
    dependencies["@radix-ui/react-slot"] = "latest";
    dependencies["class-variance-authority"] = "latest";
    dependencies["clsx"] = "latest";
    dependencies["tailwind-merge"] = "latest";
  }

  if (allContent.includes("drizzle")) {
    dependencies["drizzle-orm"] = "latest";
    devDependencies["drizzle-kit"] = "latest";
  }

  if (allContent.includes("next-auth")) {
    dependencies["next-auth"] = "latest";
  }

  const packageJson = {
    name: "generated-project",
    version: "1.0.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint",
    },
    dependencies,
    devDependencies,
  };

  return JSON.stringify(packageJson, null, 2);
}

/**
 * Generates a README.md file with setup instructions
 */
export function generateReadme(projectName: string): string {
  return `# ${projectName}

This project was generated by AI.

## Getting Started

First, install the dependencies:

\`\`\`bash
npm install
# or
yarn install
# or
pnpm install
\`\`\`

Then, run the development server:

\`\`\`bash
npm run dev
# or
yarn dev
# or
pnpm dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

## Project Structure

This is a Next.js project with the following structure:

- \`app/\` - Application pages and API routes
- \`components/\` - React components
- \`lib/\` - Utility functions and shared code
- \`public/\` - Static assets

## Learn More

To learn more about the technologies used in this project:

- [Next.js Documentation](https://nextjs.org/docs)
- [React Documentation](https://react.dev)
- [Tailwind CSS](https://tailwindcss.com/docs)

## Deploy

The easiest way to deploy your Next.js app is to use the [Vercel Platform](https://vercel.com).

Check out the [Next.js deployment documentation](https://nextjs.org/docs/deployment) for more details.
`;
}

/**
 * Generates a complete project ZIP with all necessary files
 */
export async function generateCompleteProjectZip(
  files: FileStructure[],
  projectName: string
): Promise<Blob> {
  const zip = new JSZip();

  // Add all project files
  for (const file of files) {
    zip.file(file.path, file.content);
  }

  // Add package.json
  const packageJson = generatePackageJson(files);
  zip.file("package.json", packageJson);

  // Add README.md
  const readme = generateReadme(projectName);
  zip.file("README.md", readme);

  // Add basic .gitignore
  const gitignore = `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
`;
  zip.file(".gitignore", gitignore);

  // Generate the ZIP blob
  const blob = await zip.generateAsync({ type: "blob" });
  return blob;
}
